In [1]:
import numpy as np
import pandas as pd

In [ ]:
sec_teams = [
    "Alabama", "Arkansas", "Auburn", "Florida",
    "Georgia", "Kentucky", "Louisiana State", "Mississippi",
    "Mississippi State", "Missouri", "Oklahoma", "South Carolina",
    "Tennessee", "Texas", "Texas A&M", "Vanderbilt"
]

wins = [7, 0, 1, 2, 7, 2, 3, 7, 1, 4, 6, 1, 4, 6, 7, 6]

16

In [ ]:
n = len(sec_teams)
A = np.zeros((n, n), dtype=int)

(16, 16)

In [17]:
C = np.array([
   # AL AR AU FL GA KY LS OM MS MZ OK SC TN TX AM VN
    [0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1],   # Alabama
    [0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0],   # Arkansas
    [1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1],   # Auburn
    [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0],   # Florida
    [1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0],   # Georgia
    [0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1],   # Kentucky
    [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1],   # LSU
    [0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0],   # Ole Miss
    [0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0],   # Mississippi St
    [1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],   # Missouri
    [1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0],   # Oklahoma
    [1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1],   # South Carolina
    [1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1],   # Tennessee
    [0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],   # Texas
    [0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0],   # Texas A&M
    [1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0],   # Vanderbilt
])

C *= -1
np.fill_diagonal(C, 10)
C

array([[10,  0, -1,  0, -1,  0, -1,  0,  0, -1, -1, -1, -1,  0,  0, -1],
       [ 0, 10, -1,  0,  0,  0, -1, -1, -1, -1,  0,  0, -1, -1, -1,  0],
       [-1, -1, 10,  0, -1, -1,  0,  0,  0, -1, -1,  0,  0,  0, -1, -1],
       [ 0,  0,  0, 10, -1, -1, -1, -1, -1,  0,  0,  0, -1, -1, -1,  0],
       [-1,  0, -1, -1, 10, -1,  0, -1, -1,  0,  0,  0, -1, -1,  0,  0],
       [ 0,  0, -1, -1, -1, 10,  0, -1,  0,  0,  0, -1, -1, -1,  0, -1],
       [-1, -1,  0, -1,  0,  0, 10, -1,  0,  0, -1, -1,  0,  0, -1, -1],
       [ 0, -1,  0, -1, -1, -1, -1, 10, -1,  0, -1, -1,  0,  0,  0,  0],
       [ 0, -1,  0, -1, -1,  0,  0, -1, 10, -1,  0,  0, -1, -1, -1,  0],
       [-1, -1, -1,  0,  0,  0,  0,  0, -1, 10, -1, -1,  0,  0, -1, -1],
       [-1,  0, -1,  0,  0,  0, -1, -1,  0, -1, 10, -1, -1, -1,  0,  0],
       [-1,  0,  0,  0,  0, -1, -1, -1,  0, -1, -1, 10,  0,  0, -1, -1],
       [-1, -1,  0, -1, -1, -1,  0,  0, -1,  0, -1,  0, 10,  0,  0, -1],
       [ 0, -1,  0, -1, -1, -1,  0,  0, -1,  0, -1,

In [38]:
b = np.array([i - 3 for i in wins]).reshape((n, 1))
b

array([[ 4],
       [-3],
       [-2],
       [-1],
       [ 4],
       [-1],
       [ 0],
       [ 4],
       [-2],
       [ 1],
       [ 3],
       [-2],
       [ 1],
       [ 3],
       [ 4],
       [ 3]])

In [39]:
r = np.linalg.solve(C, b)

In [40]:
r

array([[0.812184  ],
       [0.09706818],
       [0.25647858],
       [0.33488233],
       [0.78559131],
       [0.32380417],
       [0.43188876],
       [0.71998981],
       [0.22725966],
       [0.47477537],
       [0.71600316],
       [0.28340049],
       [0.49731774],
       [0.68399684],
       [0.67897502],
       [0.67638459]])

In [41]:
r[sec_teams.index("Alabama")]

array([0.812184])

In [42]:
df = pd.DataFrame({
    "Team": sec_teams,
    "Wins": wins,
    "Losses": [8 - i for i in wins],
    "Colley Rating": r.flatten()
})

df

Team  Wins  Losses  Colley Rating
0             Alabama     7       1       0.812184
1            Arkansas     0       8       0.097068
2              Auburn     1       7       0.256479
3             Florida     2       6       0.334882
4             Georgia     7       1       0.785591
5            Kentucky     2       6       0.323804
6     Louisiana State     3       5       0.431889
7         Mississippi     7       1       0.719990
8   Mississippi State     1       7       0.227260
9            Missouri     4       4       0.474775
10           Oklahoma     6       2       0.716003
11     South Carolina     1       7       0.283400
12          Tennessee     4       4       0.497318
13              Texas     6       2       0.683997
14          Texas A&M     7       1       0.678975
15         Vanderbilt     6       2       0.676385

In [37]:
df.sort_values(by="Colley Rating", ascending=False)

Team  Wins  Losses  Colley Rating
0             Alabama     7       1       0.812184
4             Georgia     7       1       0.785591
7         Mississippi     7       1       0.719990
10           Oklahoma     6       2       0.716003
13              Texas     6       2       0.683997
14          Texas A&M     7       1       0.678975
15         Vanderbilt     6       2       0.676385
12          Tennessee     4       4       0.497318
9            Missouri     4       4       0.474775
6     Louisiana State     3       5       0.431889
3             Florida     2       6       0.334882
5            Kentucky     2       6       0.323804
11     South Carolina     1       7       0.283400
2              Auburn     1       7       0.256479
8   Mississippi State     1       7       0.227260
1            Arkansas     0       8       0.097068